
version: '3.9'
services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-web-api
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
